version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: kindergarten-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

  backend:
    container_name: kindergarten-backend
    image: ${DOCKERHUB_USERNAME}/kindergarten-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      STORAGE_UPLOAD_PATH: ${STORAGE_UPLOAD_PATH}
    ports:
      - "4000:8080"
    depends_on:
      - postgres
    volumes:
      - /home/ubuntu/kindergarten-uploads:/var/kindergarten/uploads
    restart: always

  frontend:
    container_name: kindergarten-frontend
    image: ${DOCKERHUB_USERNAME}/kindergarten-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always

volumes:
  postgres_data: