version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: kindergarten-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kindergarten
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_dev_data: